# Vercel Build Output API 2.0
# https://vercel.com/docs/build-output-api/v2

version = 2

[build]
  command = "pnpm run build"
  installCommand = "pnpm install --no-frozen-lockfile"

[functions]
  directory = ".next/server/chunks"
  includeFiles = [".next/standalone/**"]

[[redirects]]
  source = "/(.*)"
  destination = "/_next/static/$1"
  permanent = true

[[headers]]
  source = "/_next/static/(.*)"
  headers = { cache-control = "public, max-age=31536000, immutable" }

[[plugins]]
  package = "@vercel/next"
